name: Hello GitHub Actions!

on:
  push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"
      - name: What time is it now?
        run: date
      - name: What's in the current directory?
        run: ls -latr
